### ISSUE TITLE
add UMD bundle for direct loading, such as CDN

### ISSUE THREAD

**Issue by TechQuery** [toeverything/intl-segmenter-polyfill-rs#18]
@toeverything for example: https://polyfill.web-cell.dev/

**Comment by fourdim** [comment]
Thank you for your suggestion. I am going to work on it soon. Possibly I will publish a seperate package for this.

BTW, please never at an organization or a team, as this will disturb all the developers and send a huge amount of unsolicit emails.
See https://news.ycombinator.com/item?id=31627061 for details.

**Comment by TechQuery** [comment]
> BTW, please never at an organization or a team, as this will disturb all the developers and send a huge amount of unsolicit emails.\nSee https://news.ycombinator.com/item?id=31627061 for details.

I'm sorry to bother you.

But GitHub has poor Notification for new issues & PRs for years, many Busy Mainteners even don't know these added items, so that replies often come out Months or Years later... 

For users, it's usually hard to find out which Developer is active, and which one should be mentioned...
